Removed command execution at case 'pageRendered' which caused TypeError
'cb' of 'pageRendered' is not a function and could not be called, so I removed call.